FROM frrouting/frr:latest

RUN sed -i 's/bgpd=no/bgpd=yes/g' /etc/frr/daemons \
	&& sed -i 's/ospfd=no/ospfd=yes/g' /etc/frr/daemons \
	&& sed -i 's/isisd=no/isisd=yes/g' /etc/frr/daemons

ENTRYPOINT ["/sbin/tini", "--"]

# Default CMD starts watchfrr
CMD ["/usr/lib/frr/docker-start"]
